common:
  cache:
    log:
      level: info
    size_bytes: 1_073_741_824
    shared_key: dev-shared-key
    api:
      bind_addr: "{{ ip }}"
      bind_port: 9090
      advertise_addr: "{{ ip }}:9090"
    cluster:
      tls:
        enabled: false
      memberlist:
        node_name: "{{ hostname }}"
        bind_address: "{{ ip }}"
        bind_port: 8946
        advertise_addr: "{{ hostname }}"
        advertise_port: 8946
        seed_dns_name: ""
        seed_dns_port: 8946
        replication_factor: 3
    seeds:
      refresh_interval_ms: 30000
    churn:
      grace_period_ms: 30000
