version: '3.9'

services:
  cache:
    image: chrismoran/infamousity:distributed-cache.0
    networks:
      - cache_control
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: replicated
      replicas: 3
    environment:
      CACHE_CLUSTER_MEMBERLIST_SEED_NODES: tasks.cache:8946

networks:
  cache_control:
    driver: overlay
    attachable: false
    internal: true
    driver_opts:
      encrypted: "true"
