version: '3.9'
services:
  node-a:
    image: chrismoran/infamousity:distributed-cache.0
    build: .
    networks:
      - cache_net
    container_name: node-a
    hostname: node-a
    ports:
      - "9090:9090"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  node-b:
    image: chrismoran/infamousity:distributed-cache.0
    build: .
    networks:
      - cache_net
    container_name: node-b
    hostname: node-b
    ports:
      - "9091:9090"
    depends_on:
      - node-a
    volumes:
      - /etc/localtime:/etc/localtime:ro
  node-c:
    image: chrismoran/infamousity:distributed-cache.0
    build: .
    networks:
      - cache_net
    container_name: node-c
    hostname: node-c
    ports:
      - "9092:9090"
    depends_on:
      - node-a
      - node-b
    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  cache_net:
    driver: overlay
    attachable: true
