// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/control/control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteConcern int32

const (
	WriteConcern_WRITE_CONCERN_ONE      WriteConcern = 0
	WriteConcern_WRITE_CONCERN_MAJORITY WriteConcern = 1
	WriteConcern_WRITE_CONCERN_REPLICA  WriteConcern = 2
)

// Enum value maps for WriteConcern.
var (
	WriteConcern_name = map[int32]string{
		0: "WRITE_CONCERN_ONE",
		1: "WRITE_CONCERN_MAJORITY",
		2: "WRITE_CONCERN_REPLICA",
	}
	WriteConcern_value = map[string]int32{
		"WRITE_CONCERN_ONE":      0,
		"WRITE_CONCERN_MAJORITY": 1,
		"WRITE_CONCERN_REPLICA":  2,
	}
)

func (x WriteConcern) Enum() *WriteConcern {
	p := new(WriteConcern)
	*p = x
	return p
}

func (x WriteConcern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteConcern) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_control_control_proto_enumTypes[0].Descriptor()
}

func (WriteConcern) Type() protoreflect.EnumType {
	return &file_internal_control_control_proto_enumTypes[0]
}

func (x WriteConcern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteConcern.Descriptor instead.
func (WriteConcern) EnumDescriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_internal_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *FetchRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Tombstone     bool                   `protobuf:"varint,4,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_internal_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *FetchResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FetchResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FetchResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FetchResponse) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlMs         int64                  `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	WriteConcern  WriteConcern           `protobuf:"varint,4,opt,name=write_concern,json=writeConcern,proto3,enum=control.WriteConcern" json:"write_concern,omitempty"`
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_internal_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *StoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StoreRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *StoreRequest) GetWriteConcern() WriteConcern {
	if x != nil {
		return x.WriteConcern
	}
	return WriteConcern_WRITE_CONCERN_ONE
}

func (x *StoreRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_internal_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{5}
}

func (x *StoreResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	WriteConcern  WriteConcern           `protobuf:"varint,2,opt,name=write_concern,json=writeConcern,proto3,enum=control.WriteConcern" json:"write_concern,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_internal_control_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetWriteConcern() WriteConcern {
	if x != nil {
		return x.WriteConcern
	}
	return WriteConcern_WRITE_CONCERN_ONE
}

func (x *DeleteRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_internal_control_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_internal_control_control_proto protoreflect.FileDescriptor

const file_internal_control_control_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/control/control.proto\x12\acontrol\"\r\n" +
	"\vPingRequest\"+\n" +
	"\fPingResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\" \n" +
	"\fFetchRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"s\n" +
	"\rFetchResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x1c\n" +
	"\ttombstone\x18\x04 \x01(\bR\ttombstone\"\xa3\x01\n" +
	"\fStoreRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\x03R\x05ttlMs\x12:\n" +
	"\rwrite_concern\x18\x04 \x01(\x0e2\x15.control.WriteConcernR\fwriteConcern\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\"\x1f\n" +
	"\rStoreResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"w\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\rwrite_concern\x18\x02 \x01(\x0e2\x15.control.WriteConcernR\fwriteConcern\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*\\\n" +
	"\fWriteConcern\x12\x15\n" +
	"\x11WRITE_CONCERN_ONE\x10\x00\x12\x1a\n" +
	"\x16WRITE_CONCERN_MAJORITY\x10\x01\x12\x19\n" +
	"\x15WRITE_CONCERN_REPLICA\x10\x022\xee\x01\n" +
	"\fControlPlane\x123\n" +
	"\x04Ping\x12\x14.control.PingRequest\x1a\x15.control.PingResponse\x126\n" +
	"\x05Fetch\x12\x15.control.FetchRequest\x1a\x16.control.FetchResponse\x126\n" +
	"\x05Store\x12\x15.control.StoreRequest\x1a\x16.control.StoreResponse\x129\n" +
	"\x06Delete\x12\x16.control.DeleteRequest\x1a\x17.control.DeleteResponseBGZEgithub.com/infamousity/distributed-cache/internal/controlpb;controlpbb\x06proto3"

var (
	file_internal_control_control_proto_rawDescOnce sync.Once
	file_internal_control_control_proto_rawDescData []byte
)

func file_internal_control_control_proto_rawDescGZIP() []byte {
	file_internal_control_control_proto_rawDescOnce.Do(func() {
		file_internal_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_control_control_proto_rawDesc), len(file_internal_control_control_proto_rawDesc)))
	})
	return file_internal_control_control_proto_rawDescData
}

var file_internal_control_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_control_control_proto_goTypes = []any{
	(WriteConcern)(0),      // 0: control.WriteConcern
	(*PingRequest)(nil),    // 1: control.PingRequest
	(*PingResponse)(nil),   // 2: control.PingResponse
	(*FetchRequest)(nil),   // 3: control.FetchRequest
	(*FetchResponse)(nil),  // 4: control.FetchResponse
	(*StoreRequest)(nil),   // 5: control.StoreRequest
	(*StoreResponse)(nil),  // 6: control.StoreResponse
	(*DeleteRequest)(nil),  // 7: control.DeleteRequest
	(*DeleteResponse)(nil), // 8: control.DeleteResponse
}
var file_internal_control_control_proto_depIdxs = []int32{
	0, // 0: control.StoreRequest.write_concern:type_name -> control.WriteConcern
	0, // 1: control.DeleteRequest.write_concern:type_name -> control.WriteConcern
	1, // 2: control.ControlPlane.Ping:input_type -> control.PingRequest
	3, // 3: control.ControlPlane.Fetch:input_type -> control.FetchRequest
	5, // 4: control.ControlPlane.Store:input_type -> control.StoreRequest
	7, // 5: control.ControlPlane.Delete:input_type -> control.DeleteRequest
	2, // 6: control.ControlPlane.Ping:output_type -> control.PingResponse
	4, // 7: control.ControlPlane.Fetch:output_type -> control.FetchResponse
	6, // 8: control.ControlPlane.Store:output_type -> control.StoreResponse
	8, // 9: control.ControlPlane.Delete:output_type -> control.DeleteResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_control_control_proto_init() }
func file_internal_control_control_proto_init() {
	if File_internal_control_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_control_control_proto_rawDesc), len(file_internal_control_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_control_control_proto_goTypes,
		DependencyIndexes: file_internal_control_control_proto_depIdxs,
		EnumInfos:         file_internal_control_control_proto_enumTypes,
		MessageInfos:      file_internal_control_control_proto_msgTypes,
	}.Build()
	File_internal_control_control_proto = out.File
	file_internal_control_control_proto_goTypes = nil
	file_internal_control_control_proto_depIdxs = nil
}
